### ISSUE TITLE
3.11.0 failed Python 3.x tests

### ISSUE THREAD

**Issue by felixonmars** [braintree/braintree_python#46]
Failed with Python 3.4.2. It works fine with Python 2.7.9. Below are the detailed errors:

```
.............................................................................E...E............................................................................................................................
======================================================================
ERROR: test_create_signature (tests.unit.test_payment_method_gateway.TestPaymentMethodGateway)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/felix/projects/arch/archlinuxcn/python-braintree/src/braintree_python-3.11.0/tests/unit/test_payment_method_gateway.py", line 67, in test_create_signature
    self.assertItemsEqual(expected_signature, actual_signature)
AttributeError: 'TestPaymentMethodGateway' object has no attribute 'assertItemsEqual'

======================================================================
ERROR: test_update_signature (tests.unit.test_payment_method_gateway.TestPaymentMethodGateway)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/felix/projects/arch/archlinuxcn/python-braintree/src/braintree_python-3.11.0/tests/unit/test_payment_method_gateway.py", line 99, in test_update_signature
    self.assertItemsEqual(expected_signature, actual_signature)
AttributeError: 'TestPaymentMethodGateway' object has no attribute 'assertItemsEqual'

----------------------------------------------------------------------
Ran 206 tests in 0.084s

FAILED (errors=2)
```

**Comment by wjr1985** [comment]
Hi felixonmars,

Thanks for letting us know about this! We're working on a fix and hope to have an update to the client library pushed out as soon as we can.

Thanks,

Bill
Braintree Developer

**Comment by wjr1985** [comment]
Hi felixonmars,

We've just released version 3.11.1 which fixes tests for Python 3.3 and higher. If you're still seeing failing tests, let us know.

Thanks,

Bill
Braintree Developer

**Comment by felixonmars** [comment]
Works fine here. Thanks!
